---

- name: Install MySQL repository
  apt:
    name: "https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm"
    state: present

- name: Install EPEL repository
  apt:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - java-1.8.0-openjdk
      - perl
      - rsync
      - ruby
      - rubygem-io-console
      - rubygem-net-ssh
      - rubygem-net-scp
      - tar
      - zip

- name: Install MySQL packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mysql-community-server
      - mysql-community-client

- name: Generate MySQL server-id
  shell: hostname -I | sed -e 's/ \+\([a-z0-9]\+\:\)\+[a-z0-9]\+//' | sed -e 's/ /\n/' | grep -v '^$' | tail -1 | awk -F. '{print $3 * 256 + $4}'
  register: mysql_server_id

- name: Create /etc/my.cnf
  template:
    src: ../templates/my.cnf.j2
    dest: /etc/my.cnf
    owner: root
    group: root
    mode: 0644
    backup: true

- name: Create /etc/init.d/mysql file
  copy:
    src: ../files/mysql
    dest: /etc/init.d/mysql
    owner: root
    group: root
    mode: 0755

- name: Enable the MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Acquire temporary root password
  shell: "awk -F': ' '$0 ~ \"temporary password\"{print $2}' /var/log/mysqld.log"
  register: mysql_root_password_temp

- name: Set new root password from default temporary password
  shell: "mysql -e \"SET PASSWORD = '{{ mysql_root_password }}';\" --connect-expired-password -uroot -p'{{ mysql_root_password_temp.stdout }}' && touch /root/.my.password.changed"
  args:
    creates: /root/.my.password.changed

- name: root to have priv with grant option
  shell: "mysql -uroot -p'{{ mysql_root_password }}' -e \"GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION; \""

